#!/bin/sh

books=$(ls -R /media/data/documents/Undergraduate | grep "pdf$")
[ "$books" = "" ] && exit 1
select=$(echo "$books" | rofi -dmenu -i -p "Select file")
[ "$select" = "" ] && exit 1
fullpath=$(find /media/data/documents/Undergraduate -name "$select" | head -n 1)
[ "$fullpath" = "" ] && exit 1
okular "$fullpath"
