#!/bin/bash
DOWNLOAD=$1
PROGRAM=$2
SUCCESS=0
if [ $DOWNLOAD = "-S" ]; then
  wget -q https://aur.archlinux.org/cgit/aur.git/snapshot/$PROGRAM.tar.gz && SUCCESS=1 || SUCCESS=0
  if [ $SUCCESS -eq 1 ]; then
    mv $PROGRAM.tar.gz ~/Documents/programs/
    cd ~/Documents/programs/
    tar -xf ~/Documents/programs/$PROGRAM.tar.gz
    cd $PROGRAM
    makepkg -si
  else
    echo Package not found.
  fi
elif [ $DOWNLOAD = "-U" ]; then
  COWER=$(cower -u | awk '{print $2}')
  if [ "$PROGRAM" = "" ]; then
    if [ "$COWER" = "" ]; then
      echo All packages are up to date.
    else
      echo Updatable packages: 
      echo $COWER | tr " " "\n"
      echo Start update? [y/n] | tr "\n" " "
      read
      if [ "$REPLY" = "y" ]; then
        for i in $COWER; do
          aurctl -S $i;
        done
      else
        echo Operation canceled.
      fi
    fi
  else
    if [ "$COWER" = "" ]; then
      echo Package not installed. Use -S instead.
    else
      aurctl -S $PROGRAM;
    fi
  fi
else
  echo Unknown parameter.
fi

