#!/bin/sh

books=$(ls -R /home/brunoesp/Documents/Books | grep "pdf$")
[ "$books" = "" ] && exit 1
select=$(echo "$books" | rofi -lines 15 -dmenu -i -p "Select file")
[ "$select" = "" ] && exit 1
fullpath=$(find /home/brunoesp/Documents/Books/"$select" | head -n 1)
[ "$fullpath" = "" ] && exit 1
zathura "$fullpath"
