#!/bin/sh

option=$(echo -e "Suspend\nReboot\nShutdown\nLock" | rofi -dmenu -lines 4 -p "Select an option")
case $option in
  "Shutdown")
    systemctl poweroff
    ;;
  "Reboot")
    systemctl reboot
    ;;
  "Suspend")
    betterlockscreen -s dim
    ;;
  "Lock")
    betterlockscreen -l dim
    ;;
  *)
    exit
    ;;
esac

