#!/bin/sh

i3lock --indicator --insidevercolor=282828ff -i /home/brunoesp/Pictures/dimblur.png --insidecolor=282828aa --ringcolor=181818aa --linecolor=282828aa --keyhlcolor=b5e8c3ff --veriftext="" --ringvercolor=b5e8c3aa --wrongtext="" --insidewrongcolor=ff6969ff --ringwrongcolor=b5e8c3ff
