#!/bin/bash
option=$1
case $option in
  "-s")
    maim -q -s | tee ~/Images/Screenshots/Screenshot_$(date +%Y%m%d_%H%M%S).png /tmp/temp_pic.png > /dev/null && xclip -selection clipboard -t image/png -i /tmp/temp_pic.png
    ;;
  "-i")
    maim -q -i $(xdotool getactivewindow) | tee ~/Images/Screenshots/Screenshot_$(date +%Y%m%d_%H%M%S).png /tmp/temp_pic.png > /dev/null && xclip -selection clipboard -t image/png -i /tmp/temp_pic.png
    ;;
     *)
    maim -q | tee ~/Images/Screenshots/Screenshot_$(date +%Y%m%d_%H%M%S).png /tmp/temp_pic.png > /dev/null && xclip -selection clipboard -t image/png -i /tmp/temp_pic.png
    ;;
esac
